#include<stdio.h>
#include<conio.h>
void main()
{
  int k=15,r=3,i;
  clrscr();

   // sam of k,r //

  i=k+r;
  printf(" sam of k+r=%d",i);

   // subtraction of k,r //

  i=k-r;
  printf("\n subtraction of k-r=%d",i);

   // multiplication of k,r //

  i=k*r;
  printf("\n multiplication of k*r=%d",i);

   // divison of k,r //

  i=k/r;
  printf("\n divison of k/r=%d",i);

  getch();
  }